apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "legacy-web.name" . }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{- include "legacy-web.selector" . | nindent 6 }}
